sudo: required
services:
  - docker

before_install:
  - docker build -t ravi2908/docker-go -f Dockerfile.dev .

script:
  - docker run ravi2908/docker-go go test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Golang"
  env: "Golang-env"
  bucket_name: "elasticbeanstalk-us-east-2-523416944462"
  bucket_path: "Golang"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
